// Course-ordered cards added from the Summer GERM1001 outline, Miss's lesson
// notes (Lektion 12-17), and the referenced Themen 1 Aktuell coursebook.
window.courseOutlineCards = [
  // Lektion 12 / Outline: Wohnen
  { category: "Week 3 · Wohnen & Dativ", german: "Wo ist der Tisch?", english: "Where is the table?", note: "Lektion 12-13: Wo? asks for a location and takes the dative after a two-way preposition." },
  { category: "Week 3 · Wohnen & Dativ", german: "Der Tisch steht im Wohnzimmer.", english: "The table is in the living room.", note: "im = in dem (dative)." },
  { category: "Week 3 · Wohnen & Dativ", german: "Das Bild hängt an der Wand.", english: "The picture hangs on the wall.", note: "Location: an + dative." },
  { category: "Week 3 · Wohnen & Dativ", german: "Die Lampe steht auf dem Tisch.", english: "The lamp is on the table.", note: "Location: auf + dative." },
  { category: "Week 3 · Wohnen & Dativ", german: "Der Sessel steht neben dem Sofa.", english: "The armchair is beside the sofa.", note: "Location: neben + dative." },
  { category: "Week 3 · Wohnen & Dativ", german: "Der Schrank steht zwischen dem Fenster und der Tür.", english: "The wardrobe is between the window and the door.", note: "Location: zwischen + dative." },
  { category: "Week 3 · Wohnen & Dativ", german: "für + Akkusativ", english: "for + accusative", note: "Lektion 12, page 59. Example: Das Zimmer ist für einen Studenten." },
  { category: "Week 3 · Wohnen & Dativ", german: "Das Zimmer ist für einen Studenten.", english: "The room is for a male student.", note: "für always takes the accusative; masculine ein becomes einen." },
  { category: "Week 3 · Wohnen & Dativ", german: "Wie findest du den Tisch? - Den finde ich schön.", english: "How do you like the table? - I think it is beautiful.", note: "Lektion 12: definite pronoun den replaces a masculine accusative noun." },
  { category: "Week 3 · Wohnen & Dativ", german: "Wie findest du die Lampe? - Die finde ich modern.", english: "How do you like the lamp? - I think it is modern.", note: "Definite pronoun die replaces a feminine noun." },
  { category: "Week 3 · Wohnen & Dativ", german: "Wie findest du das Sofa? - Das finde ich bequem.", english: "How do you like the sofa? - I think it is comfortable.", note: "Definite pronoun das replaces a neuter noun." },
  { category: "Week 3 · Wohnen & Dativ", german: "die Wohnung / die Wohnungen", english: "apartment / apartments", note: "Housing vocabulary from Lektion 12." },
  { category: "Week 3 · Wohnen & Dativ", german: "die Miete", english: "rent", note: "Useful for reading housing advertisements." },
  { category: "Week 3 · Wohnen & Dativ", german: "der Wohnungsmarkt", english: "housing market", note: "Coursebook page 62." },

  // Lektion 13-14 / Outline outcome 7: Krankheit
  { category: "Weeks 3-4 · Körper & Krankheit", german: "der Kopf", english: "head", note: "Body-part vocabulary, coursebook page 70." },
  { category: "Weeks 3-4 · Körper & Krankheit", german: "das Auge", english: "eye", note: "Plural: die Augen." },
  { category: "Weeks 3-4 · Körper & Krankheit", german: "die Nase", english: "nose", note: "Body part." },
  { category: "Weeks 3-4 · Körper & Krankheit", german: "der Mund", english: "mouth", note: "Body part." },
  { category: "Weeks 3-4 · Körper & Krankheit", german: "das Ohr", english: "ear", note: "Plural: die Ohren." },
  { category: "Weeks 3-4 · Körper & Krankheit", german: "das Gesicht", english: "face", note: "Body part." },
  { category: "Weeks 3-4 · Körper & Krankheit", german: "die Zähne", english: "teeth", note: "Singular: der Zahn." },
  { category: "Weeks 3-4 · Körper & Krankheit", german: "der Hals", english: "throat / neck", note: "Body part." },
  { category: "Weeks 3-4 · Körper & Krankheit", german: "der Rücken", english: "back", note: "Body part." },
  { category: "Weeks 3-4 · Körper & Krankheit", german: "die Brust", english: "chest / breast", note: "Body part." },
  { category: "Weeks 3-4 · Körper & Krankheit", german: "der Bauch", english: "stomach / belly", note: "Body part." },
  { category: "Weeks 3-4 · Körper & Krankheit", german: "der Arm", english: "arm", note: "Plural: die Arme." },
  { category: "Weeks 3-4 · Körper & Krankheit", german: "die Hand", english: "hand", note: "Plural: die Hände." },
  { category: "Weeks 3-4 · Körper & Krankheit", german: "der Finger", english: "finger", note: "Plural: die Finger." },
  { category: "Weeks 3-4 · Körper & Krankheit", german: "das Bein", english: "leg", note: "Plural: die Beine." },
  { category: "Weeks 3-4 · Körper & Krankheit", german: "das Knie", english: "knee", note: "Plural: die Knie." },
  { category: "Weeks 3-4 · Körper & Krankheit", german: "der Fuß", english: "foot", note: "Plural: die Füße." },
  { category: "Weeks 3-4 · Körper & Krankheit", german: "Mein Kopf tut mir weh.", english: "My head hurts.", note: "Lektion 13 pattern: singular body part + tut (mir) weh." },
  { category: "Weeks 3-4 · Körper & Krankheit", german: "Meine Füße tun weh.", english: "My feet hurt.", note: "Plural body parts take tun weh." },
  { category: "Weeks 3-4 · Körper & Krankheit", german: "Ich habe Kopfschmerzen.", english: "I have a headache.", note: "Lektion 13 pattern: Körperteil + Schmerzen." },
  { category: "Weeks 3-4 · Körper & Krankheit", german: "Ich habe Halsschmerzen.", english: "I have a sore throat.", note: "Health complaint." },
  { category: "Weeks 3-4 · Körper & Krankheit", german: "Ich habe Bauchschmerzen.", english: "I have a stomachache.", note: "Health complaint." },
  { category: "Weeks 3-4 · Körper & Krankheit", german: "Ich habe Zahnschmerzen.", english: "I have a toothache.", note: "Health complaint." },
  { category: "Weeks 3-4 · Körper & Krankheit", german: "Ich habe Fieber.", english: "I have a fever.", note: "Health complaint." },
  { category: "Weeks 3-4 · Körper & Krankheit", german: "Ich bin erkältet.", english: "I have a cold.", note: "Literally: I am suffering from a cold." },
  { category: "Weeks 3-4 · Körper & Krankheit", german: "Ich habe Grippe.", english: "I have the flu.", note: "Health complaint." },
  { category: "Weeks 3-4 · Körper & Krankheit", german: "Ich kann nicht schlafen.", english: "I cannot sleep.", note: "Useful for describing sleep problems." },

  // Doctor visits and advice
  { category: "Week 4 · Beim Arzt", german: "Ich möchte einen Termin vereinbaren.", english: "I would like to make an appointment.", note: "Lektion 14: making a doctor's appointment." },
  { category: "Week 4 · Beim Arzt", german: "Haben Sie heute einen Termin frei?", english: "Do you have an appointment available today?", note: "Formal appointment question." },
  { category: "Week 4 · Beim Arzt", german: "Wann können Sie kommen?", english: "When can you come?", note: "Formal question from an appointment conversation." },
  { category: "Week 4 · Beim Arzt", german: "Um zehn Uhr passt es mir.", english: "Ten o'clock works for me.", note: "Confirming an appointment time." },
  { category: "Week 4 · Beim Arzt", german: "Was fehlt Ihnen?", english: "What is wrong with you?", note: "Formal doctor's question." },
  { category: "Week 4 · Beim Arzt", german: "Wo tut es weh?", english: "Where does it hurt?", note: "Doctor's question." },
  { category: "Week 4 · Beim Arzt", german: "Seit wann haben Sie Schmerzen?", english: "Since when have you had pain?", note: "Formal health question." },
  { category: "Week 4 · Beim Arzt", german: "Sie sollen im Bett bleiben.", english: "You should stay in bed.", note: "sollen gives advice or reports an instruction." },
  { category: "Week 4 · Beim Arzt", german: "Sie müssen viel Wasser trinken.", english: "You must drink plenty of water.", note: "Health advice with müssen." },
  { category: "Week 4 · Beim Arzt", german: "Sie dürfen nicht rauchen.", english: "You must not smoke.", note: "nicht dürfen means not be allowed to." },
  { category: "Week 4 · Beim Arzt", german: "Nehmen Sie diese Tabletten.", english: "Take these tablets.", note: "Formal imperative used by a doctor." },
  { category: "Week 4 · Beim Arzt", german: "Gute Besserung!", english: "Get well soon!", note: "Wish for someone who is ill." },

  // Lektion 15-16 / Outline outcome 8: past tense
  { category: "Week 4 · Perfekt Basics", german: "haben/sein + Partizip II", english: "present-perfect structure", note: "The helper is conjugated in position 2; the participle normally goes at the end." },
  { category: "Week 4 · Perfekt Basics", german: "Ich habe am Wochenende gearbeitet.", english: "I worked at the weekend.", note: "Most verbs form the Perfekt with haben." },
  { category: "Week 4 · Perfekt Basics", german: "Was hast du am Wochenende gemacht?", english: "What did you do at the weekend?", note: "Key Lektion 16 speaking/writing prompt." },
  { category: "Week 4 · Perfekt Basics", german: "machen - hat gemacht", english: "to do/make - did/has done", note: "Regular participle: ge + stem + t." },
  { category: "Week 4 · Perfekt Basics", german: "arbeiten - hat gearbeitet", english: "to work - worked/has worked", note: "An extra e makes gearbeitet pronounceable." },
  { category: "Week 4 · Perfekt Basics", german: "lernen - hat gelernt", english: "to learn - learned/has learned", note: "Regular participle." },
  { category: "Week 4 · Perfekt Basics", german: "kochen - hat gekocht", english: "to cook - cooked/has cooked", note: "Regular participle." },
  { category: "Week 4 · Perfekt Basics", german: "kaufen - hat gekauft", english: "to buy - bought/has bought", note: "Regular participle." },
  { category: "Week 4 · Perfekt Basics", german: "spielen - hat gespielt", english: "to play - played/has played", note: "Regular participle." },
  { category: "Week 4 · Perfekt Basics", german: "aufräumen - hat aufgeräumt", english: "to tidy up - tidied up/has tidied up", note: "Separable verb: ge goes between prefix and stem." },
  { category: "Week 4 · Perfekt Basics", german: "einkaufen - hat eingekauft", english: "to shop - shopped/has shopped", note: "Separable verb." },
  { category: "Week 4 · Perfekt Basics", german: "studieren - hat studiert", english: "to study - studied/has studied", note: "Verbs ending in -ieren do not add ge-." },
  { category: "Week 4 · Perfekt Basics", german: "besuchen - hat besucht", english: "to visit - visited/has visited", note: "Inseparable be- prefix: no ge-." },
  { category: "Week 4 · Perfekt Basics", german: "essen - hat gegessen", english: "to eat - ate/has eaten", note: "Irregular participle." },
  { category: "Week 4 · Perfekt Basics", german: "trinken - hat getrunken", english: "to drink - drank/has drunk", note: "Irregular participle." },
  { category: "Week 4 · Perfekt Basics", german: "sehen - hat gesehen", english: "to see - saw/has seen", note: "Irregular participle." },
  { category: "Week 4 · Perfekt Basics", german: "schreiben - hat geschrieben", english: "to write - wrote/has written", note: "Irregular participle." },
  { category: "Week 4 · Perfekt Basics", german: "nehmen - hat genommen", english: "to take - took/has taken", note: "Irregular participle." },
  { category: "Week 4 · Perfekt Basics", german: "helfen - hat geholfen", english: "to help - helped/has helped", note: "Irregular participle." },

  { category: "Weeks 4-5 · Perfekt mit sein", german: "Ich bin nach Hause gegangen.", english: "I went home.", note: "Use sein with movement from one place to another." },
  { category: "Weeks 4-5 · Perfekt mit sein", german: "gehen - ist gegangen", english: "to go - went/has gone", note: "Movement verb: sein." },
  { category: "Weeks 4-5 · Perfekt mit sein", german: "kommen - ist gekommen", english: "to come - came/has come", note: "Movement verb: sein." },
  { category: "Weeks 4-5 · Perfekt mit sein", german: "fahren - ist gefahren", english: "to travel/drive - travelled/has travelled", note: "Movement verb: sein." },
  { category: "Weeks 4-5 · Perfekt mit sein", german: "fliegen - ist geflogen", english: "to fly - flew/has flown", note: "Movement verb: sein." },
  { category: "Weeks 4-5 · Perfekt mit sein", german: "schwimmen - ist geschwommen", english: "to swim - swam/has swum", note: "Use sein when the focus is movement to a destination." },
  { category: "Weeks 4-5 · Perfekt mit sein", german: "aufstehen - ist aufgestanden", english: "to get up - got up/has gotten up", note: "Change of state; separable verb." },
  { category: "Weeks 4-5 · Perfekt mit sein", german: "fallen - ist gefallen", english: "to fall - fell/has fallen", note: "Change of state/movement: sein." },
  { category: "Weeks 4-5 · Perfekt mit sein", german: "bleiben - ist geblieben", english: "to stay - stayed/has stayed", note: "Important exception that uses sein." },
  { category: "Weeks 4-5 · Perfekt mit sein", german: "sein - ist gewesen", english: "to be - was/has been", note: "Perfect form of sein." },
  { category: "Weeks 4-5 · Perfekt mit sein", german: "haben - hat gehabt", english: "to have - had/has had", note: "Perfect form of haben." },
  { category: "Weeks 4-5 · Perfekt mit sein", german: "Ich war krank.", english: "I was ill.", note: "Lektion 16: simple past of sein; ich/er/sie/es war." },
  { category: "Weeks 4-5 · Perfekt mit sein", german: "Ich hatte keine Zeit.", english: "I had no time.", note: "Lektion 16: simple past of haben; ich/er/sie/es hatte." },

  { category: "Week 5 · Monate & Vergangenheit", german: "Januar", english: "January", note: "Month of the year." },
  { category: "Week 5 · Monate & Vergangenheit", german: "Februar", english: "February", note: "Month of the year." },
  { category: "Week 5 · Monate & Vergangenheit", german: "März", english: "March", note: "Month of the year." },
  { category: "Week 5 · Monate & Vergangenheit", german: "April", english: "April", note: "Month of the year." },
  { category: "Week 5 · Monate & Vergangenheit", german: "Mai", english: "May", note: "Month of the year." },
  { category: "Week 5 · Monate & Vergangenheit", german: "Juni", english: "June", note: "Month of the year." },
  { category: "Week 5 · Monate & Vergangenheit", german: "Juli", english: "July", note: "Month of the year." },
  { category: "Week 5 · Monate & Vergangenheit", german: "August", english: "August", note: "Month of the year." },
  { category: "Week 5 · Monate & Vergangenheit", german: "September", english: "September", note: "Month of the year." },
  { category: "Week 5 · Monate & Vergangenheit", german: "Oktober", english: "October", note: "Month of the year." },
  { category: "Week 5 · Monate & Vergangenheit", german: "November", english: "November", note: "Month of the year." },
  { category: "Week 5 · Monate & Vergangenheit", german: "Dezember", english: "December", note: "Month of the year." },
  { category: "Week 5 · Monate & Vergangenheit", german: "letztes Jahr", english: "last year", note: "Past-time expression." },
  { category: "Week 5 · Monate & Vergangenheit", german: "letzten Monat", english: "last month", note: "Past-time expression (accusative time phrase)." },
  { category: "Week 5 · Monate & Vergangenheit", german: "gestern", english: "yesterday", note: "Past-time expression." },
  { category: "Week 5 · Monate & Vergangenheit", german: "am Wochenende", english: "at the weekend", note: "Time expression used in the Lektion 16 prompt." },

  // Lektion 17 / Outline: Alltag and orientation
  { category: "Week 5 · Alltag im Perfekt", german: "Um sieben Uhr bin ich aufgestanden.", english: "At seven o'clock I got up.", note: "Model for the Lektion 17 daily-routine assignment." },
  { category: "Week 5 · Alltag im Perfekt", german: "Dann habe ich gefrühstückt.", english: "Then I ate breakfast.", note: "Daily routine in the Perfekt." },
  { category: "Week 5 · Alltag im Perfekt", german: "Ich habe meine Zähne geputzt.", english: "I brushed my teeth.", note: "Daily routine in the Perfekt." },
  { category: "Week 5 · Alltag im Perfekt", german: "Ich bin zur Universität gefahren.", english: "I travelled to the university.", note: "Movement to a destination uses sein." },
  { category: "Week 5 · Alltag im Perfekt", german: "Ich habe Deutsch gelernt.", english: "I studied German.", note: "Daily routine in the Perfekt." },
  { category: "Week 5 · Alltag im Perfekt", german: "Ich bin nach Hause gekommen.", english: "I came home.", note: "Movement verb with sein." },
  { category: "Week 5 · Alltag im Perfekt", german: "Am Abend habe ich ferngesehen.", english: "In the evening I watched television.", note: "fernsehen is separable: hat ferngesehen." },
  { category: "Week 5 · Alltag im Perfekt", german: "Um elf Uhr bin ich ins Bett gegangen.", english: "At eleven o'clock I went to bed.", note: "Movement verb with sein." },

  { category: "Week 5 · Wohin & Akkusativ", german: "Wo? - Dativ / Wohin? - Akkusativ", english: "Where? - dative / Where to? - accusative", note: "Lektion 13 and 17 contrast: location versus destination." },
  { category: "Week 5 · Wohin & Akkusativ", german: "Wohin gehst du?", english: "Where are you going?", note: "Asks for a destination." },
  { category: "Week 5 · Wohin & Akkusativ", german: "Ich gehe in ein Café.", english: "I am going into a café.", note: "Lektion 17 example: destination with in + accusative." },
  { category: "Week 5 · Wohin & Akkusativ", german: "Ich gehe in den Kindergarten.", english: "I am going into the kindergarten.", note: "Masculine accusative destination." },
  { category: "Week 5 · Wohin & Akkusativ", german: "Ich gehe in die Schule.", english: "I am going into/to the school.", note: "Feminine accusative destination." },
  { category: "Week 5 · Wohin & Akkusativ", german: "Ich gehe ins Büro.", english: "I am going into/to the office.", note: "ins = in das (accusative)." },
  { category: "Week 5 · Wohin & Akkusativ", german: "Ich gehe nach Hause.", english: "I am going home.", note: "Fixed destination phrase without an article." },
  { category: "Week 5 · Wohin & Akkusativ", german: "Ich gehe zur Haltestelle.", english: "I am going to the bus/tram stop.", note: "zur = zu der; zu always takes dative even though it answers Wohin?" },

  { category: "Week 5 · Stadt & Orientierung", german: "Entschuldigung, wo ist der Bahnhof?", english: "Excuse me, where is the train station?", note: "Outline Week 5: asking for directions." },
  { category: "Week 5 · Stadt & Orientierung", german: "Wie komme ich zum Bahnhof?", english: "How do I get to the train station?", note: "zum = zu dem." },
  { category: "Week 5 · Stadt & Orientierung", german: "Gehen Sie geradeaus.", english: "Go straight ahead.", note: "Formal direction." },
  { category: "Week 5 · Stadt & Orientierung", german: "Gehen Sie nach links.", english: "Go left.", note: "Formal direction." },
  { category: "Week 5 · Stadt & Orientierung", german: "Gehen Sie nach rechts.", english: "Go right.", note: "Formal direction." },
  { category: "Week 5 · Stadt & Orientierung", german: "Nehmen Sie die erste Straße links.", english: "Take the first street on the left.", note: "Formal direction." },
  { category: "Week 5 · Stadt & Orientierung", german: "an der Ecke", english: "at the corner", note: "Location phrase with dative." },
  { category: "Week 5 · Stadt & Orientierung", german: "neben der Apotheke", english: "beside the pharmacy", note: "Location phrase with dative." },
  { category: "Week 5 · Stadt & Orientierung", german: "gegenüber dem Supermarkt", english: "opposite the supermarket", note: "gegenüber takes the dative." },
  { category: "Week 5 · Stadt & Orientierung", german: "zwischen der Bank und dem Hotel", english: "between the bank and the hotel", note: "Location with dative." },
  { category: "Week 5 · Stadt & Orientierung", german: "der Bahnhof", english: "train station", note: "City vocabulary." },
  { category: "Week 5 · Stadt & Orientierung", german: "die Apotheke", english: "pharmacy", note: "City vocabulary." },
  { category: "Week 5 · Stadt & Orientierung", german: "die Bushaltestelle", english: "bus stop", note: "City vocabulary." },
  { category: "Week 5 · Stadt & Orientierung", german: "die Kreuzung", english: "intersection", note: "City vocabulary." },

  // Final outline topic
  { category: "Week 6 · Kaufen & Schenken", german: "Kann ich Ihnen helfen?", english: "Can I help you?", note: "Outline Week 6: shopping interaction." },
  { category: "Week 6 · Kaufen & Schenken", german: "Ich suche eine Jacke.", english: "I am looking for a jacket.", note: "Shopping phrase." },
  { category: "Week 6 · Kaufen & Schenken", german: "Haben Sie das in Größe M?", english: "Do you have that in size M?", note: "Formal shopping question." },
  { category: "Week 6 · Kaufen & Schenken", german: "Kann ich das anprobieren?", english: "Can I try that on?", note: "anprobieren is separable." },
  { category: "Week 6 · Kaufen & Schenken", german: "Wo ist die Umkleidekabine?", english: "Where is the changing room?", note: "Shopping question." },
  { category: "Week 6 · Kaufen & Schenken", german: "Die Jacke passt mir gut.", english: "The jacket fits me well.", note: "passen takes a dative person: mir." },
  { category: "Week 6 · Kaufen & Schenken", german: "Das Hemd ist zu groß.", english: "The shirt is too large.", note: "Clothing description." },
  { category: "Week 6 · Kaufen & Schenken", german: "Die Hose ist zu klein.", english: "The trousers are too small.", note: "In German, Hose is singular." },
  { category: "Week 6 · Kaufen & Schenken", german: "Wie viel kostet das?", english: "How much does that cost?", note: "Shopping question." },
  { category: "Week 6 · Kaufen & Schenken", german: "Ich nehme es.", english: "I'll take it.", note: "Use after deciding to buy a neuter item." },
  { category: "Week 6 · Kaufen & Schenken", german: "Das ist ein Geschenk für meine Mutter.", english: "That is a gift for my mother.", note: "für takes the accusative." },
  { category: "Week 6 · Kaufen & Schenken", german: "die Jacke", english: "jacket", note: "Clothing vocabulary." },
  { category: "Week 6 · Kaufen & Schenken", german: "das Hemd", english: "shirt", note: "Clothing vocabulary." },
  { category: "Week 6 · Kaufen & Schenken", german: "die Hose", english: "trousers / pants", note: "Clothing vocabulary." },
  { category: "Week 6 · Kaufen & Schenken", german: "das Kleid", english: "dress", note: "Clothing vocabulary." },
  { category: "Week 6 · Kaufen & Schenken", german: "die Schuhe", english: "shoes", note: "Usually used in the plural." },
  { category: "Week 6 · Kaufen & Schenken", german: "der Pullover", english: "sweater", note: "Clothing vocabulary." }
];
